name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - faiss-gpu
  - scikit-learn
  - jupyter
  - python-dotenv
  - filelock  
  - pip:
      - torch==2.1.0+cu118
      - torchvision==0.16.0+cu118
      - torchaudio==2.1.0+cu118
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - sentence-transformers
      - langchain
      - openai
      - chromadb
      - easyocr
      - ipykernel
      - langchain-community
      - pymupdf
